### ISSUE TITLE
Example: show_chars_in_window is broken

### ISSUE THREAD

**Issue by neilpate** [phip1611/noto-sans-mono-bitmap-rs#10]
The `FontWeight::Light` and `RasterHeight::Size32` enum items chosen are not enabled.

The only items enabled are `Regular` and `Size16` respectively.

![image](https://user-images.githubusercontent.com/7802334/211904345-2829ebf4-5d54-47dd-bb0e-6bad1e435b4d.png)

**Comment by neilpate** [comment]
Changing the items to `Regular`and `Size16`allows the code to be run, but it then panics (for a different reason, will file a separate issue).

**Comment by phip1611** [comment]
Hi, thanks for reporting that issue. I'll look into it and make sure that CI catches this the next time.
