### ISSUE TITLE
Example: show_chars_in_window panics on run

### ISSUE THREAD

**Issue by neilpate** [phip1611/noto-sans-mono-bitmap-rs#11]
The code is initally broken, as mentioned in #10, but after fixing this when the code is run it panics due to an unknown char.

` Compiling noto-sans-mono-bitmap v0.2.0 (C:\dev\Rust\noto-sans-mono-bitmap-rs)
    Finished dev [unoptimized + debuginfo] target(s) in 0.47s
     Running `target\debug\examples\show_chars_in_window.exe`
thread 'main' panicked at 'unknown char', examples\show_chars_in_window.rs:18:72
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\panicking.rs:142
   2: core::panicking::panic_display<str>
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\panicking.rs:72
   3: core::panicking::panic_str
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\panicking.rs:56
   4: core::option::expect_failed
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\option.rs:1880
   5: enum2$<core::option::Option<noto_sans_mono_bitmap::RasterizedChar> >::expect<noto_sans_mono_bitmap::RasterizedChar>
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\option.rs:738
   6: show_chars_in_window::main
             at .\examples\show_chars_in_window.rs:18
   7: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\ops\function.rs:248
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\examples\show_chars_in_window.exe` (exit code: 101)

 *  The terminal process "C:\Users\neilp\.cargo\bin\cargo.exe 'run', '--package', 'noto-sans-mono-bitmap', '--example', 'show_chars_in_window'" terminated with exit code: 101. `

**Removing the unicode characters from `msg`fixes the problem.**

![image](https://user-images.githubusercontent.com/7802334/211905358-15160ba0-3c76-4bd7-aa81-8aef383e71be.png)

![image](https://user-images.githubusercontent.com/7802334/211905425-b251d637-52e0-4069-acd2-361affcb84f4.png)

**Comment by phip1611** [comment]
Yes, by default, only the latin unicode range is available. I forgot that.

I decided to remove those symbols. Alternatively, one can run `cargo run --example show_chars_in_window --features all`

**Comment by phip1611** [comment]
Fixed
