### ISSUE TITLE
Size16 q and g basically identical.

### ISSUE THREAD

**Issue by Benabik** [phip1611/noto-sans-mono-bitmap-rs#14]
Basically only the bottom row of pixels are different, with none of them being more than value 100.  This makes it basically impossible to see.  Perhaps the characters should be shifted up and/or shrunk slightly?

<img width="69" alt="Screenshot 2023-02-08 at 11 45 12 PM" src="https://user-images.githubusercontent.com/133455/217720236-9a990813-dd59-4735-8036-d823a959daee.png">

**Comment by phip1611** [comment]
Hey, thanks for the bug report. I'll look into it.

**Comment by phip1611** [comment]
![image](https://user-images.githubusercontent.com/5737016/218337436-7e919b0b-baed-44b5-af2a-9d410c545fe0.png)

right: current state
left: move letter 1px upwards in the box

With the additional 1px offset, the font alignment does look better, indeed. However,
it minimally truncates the two points letters such as "Ä".

**Comment by Benabik** [comment]
I think that's a notable improvement.  I honestly thought my rendering was wrong b/c `g` looked so wrong.  The Ä being against the top would be unfortunate if it's below something against the bottom (like g), but I think Ä is rarer than g even in languages that use it.  YMMV

**Comment by phip1611** [comment]
fixed with https://github.com/phip1611/noto-sans-mono-bitmap-rs/pull/17
