### ISSUE TITLE
how do i make the background transparent when text is displayed in the minifb.

### ISSUE THREAD

**Issue by Ykong1337** [phip1611/noto-sans-mono-bitmap-rs#9]
when i build text in minifb, the text always has it's own background, how can i make its background transparent, or remove its background.
![image](https://user-images.githubusercontent.com/66518156/199409771-161b5739-6260-471f-a945-7e17a5a17f33.png)

**Comment by phip1611** [comment]
Hey! Can you please give me a little more context? Which code are you using? Did you write code by yourself or have you adapted one of my examples?

**Comment by Ykong1337** [comment]
```

**Comment by Ykong1337** [comment]
```
use minifb::{Key, Window, WindowOptions};
use noto_sans_mono_bitmap::{get_raster, FontWeight, RasterHeight};

// Example that prints the chars in var "msg" to the screen using
// the pre-rendered bitmap font.
fn main() {
    // letters we want to print
    let msg = "Abc ! Hello world!";
    let font_weight = FontWeight::Regular;
    let raster_height = RasterHeight::Size32;
    let mut draw_buffer = vec![0; 640 * 480];

    // rasterize each char and draw it into the framebuffer
    for (char_i, char) in msg.chars().enumerate() {
        let char_raster = get_raster(char, font_weight, raster_height).unwrap();
        for (row_i, row) in char_raster.raster().iter().enumerate() {
            for (col_i, intensity) in row.iter().enumerate() {
                let (r, g, b) = (*intensity as u32, *intensity as u32, *intensity as u32);
                let (r, g, b) = (255 - r, 255 - g, 255 - b);
                let rgb_32 = /*0 << 24 | */r << 16 | g << 8 | b;

                let index = char_i * char_raster.width() + col_i + row_i * 640;

                draw_buffer[index] = rgb_32;
            }
        }
    }

    let mut window = Window::new("Test - ESC to exit", 640, 480, WindowOptions::default()).unwrap();

    while window.is_open() && !window.is_key_down(Key::Escape) {
        // We unwrap here as we want this code to exit if it fails. Real applications may want to handle this in a different way


        window.update_with_buffer(&draw_buffer, 640, 480).unwrap();
    }
}
```

**Comment by phip1611** [comment]
`let (r, g, b) = (255 - r, 255 - g, 255 - b);`

You are literally setting each pixel to white with that, if there is no font pixel on it. I'm not sure how to solve this best. Probably, instead of `255 -` you can use the background color as a base value there - something like that. @Ykong1337

**Comment by Ykong1337** [comment]
> `let (r, g, b) = (255 - r, 255 - g, 255 - b);`
> 
> You are literally setting each pixel to white with that, if there is no font pixel on it. I'm not sure how to solve this best. Probably, instead of `255 -` you can use the background color as a base value there - something like that. @Ykong1337

OK, i try to make its background color the same color as minifb background. even if it is resolved.😂
